config/routes.rb
Rails.application.routes.draw do
  resources :images
  resources :users, only: [:index, :show] do
    member do
      get :following
      get :followers
    end
  end
  resources :follows, only: [:create, :destroy]
  devise_for :users, :controllers => { registrations: 'registrations' }
  get 'welcome/index'
  root 'welcome#index'
  get 'users', to: 'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :user
  mount_uploader :picture, PictureUploader

  validates :name, presence: true
  validates :picture, presence: true
end

app/models/payment.rb
class Payment < ApplicationRecord
  attr_accessor :card_number, :card_cvv, :card_expires_month, :card_expires_year
  belongs_to :user

  validates :token, presence: true
  validates :email, presence: true

  def self.month_options
    Date::MONTHNAMES.compact.each_with_index.map { |name, i| ["#{i+1} - #{name}", i+1]}
  end

  def self.year_options
    (Date.today.year..(Date.today.year+10)).to_a
  end

  def process_payment
    customer = Stripe::Customer.create({ email: email, source: token })

    Stripe::Charge.create(customer: customer.id, amount: 1000, description: 'Premium', currency: 'usd')

  rescue Exception => e
    Rails.logger.error "Stripe Error: #{e.class} - #{e.message}"
    flash[:error] = "Payment error: #{e.message}"
    resource.destroy
    render :new and return
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable

  has_one :payment
  accepts_nested_attributes_for :payment

  has_many :images

  has_many :active_follows, class_name: "Follow", foreign_key: "follower_id", dependent: :destroy
  has_many :following, through: :active_follows, source: :followed

  has_many :passive_follows, class_name: "Follow", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :passive_follows, source: :follower


  def full_name
    if name.present? || lastname.present?
      "#{name} #{lastname}"
    else
      "Anonymous"
    end
  end

  def follow(other_user)
    following << other_user unless self == other_user || following.include?(other_user)
  end

  def unfollow(other_user)
    following.delete(other_user)
  end

  def following?(other_user)
    following.include?(other_user)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    added_attrs = [:name, :lastname, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit(:sign_up, keys: added_attrs)
    devise_parameter_sanitizer.permit(:account_update, keys: added_attrs)
  end
end

app/controllers/dummy_controller.rb
class DummyController < ApplicationController
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  before_action :authenticate_user!

  def create
    user = User.find(params[:followed_id])
    current_user.following << user
    redirect_to user
  end

  def destroy
    user = Follow.find(params[:id]).followed
    current_user.following.delete(user)
    redirect_to user
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: %i[ show edit update destroy ]

  # GET /images or /images.json
  def index
    @images = Image.all
  end

  # GET /images/1 or /images/1.json
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images or /images.json
  def create
    @image = Image.new(image_params)
    @image.user = current_user

    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: "Image was successfully created." }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1 or /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: "Image was successfully updated." }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1 or /images/1.json
  def destroy
    @image.destroy

    respond_to do |format|
      format.html { redirect_to images_path, status: :see_other, notice: "Image was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def image_params
      params.require(:image).permit(:name, :picture, :user_id)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters, if: :devise_controller?

  def create
    build_resource(sign_up_params)

    resource.class.transaction do
      resource.save
      yield resource if block_given?
      if resource.persisted?
        @payment = Payment.new({ email: params["user"]["email"], token: params[:payment]["token"], user_id: resource.id })

        flash[:error] = "Please check registration errors" unless @payment.valid?

        begin
          @payment.process_payment
          @payment.save
        rescue Exception => e
          flash[:error] = e.message
          resource.destroy
          render :new and return
        end

        if resource.active_for_authentication?
          set_flash_message :notice, :signed_up if is_flashing_format?
          sign_up(resource_name, resource)
          respond_with resource, location: after_sign_up_path_for(resource)
        else
          set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_flashing_format?
          expire_data_after_sign_in!
          respond_with resource, location: after_inactive_sign_up_path_for(resource)
        end
      else
        clean_up_passwords resource
        set_minimum_password_length
        respond_with resource
      end
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :lastname])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :following, :followers]
  def index
    @users = User.all
  end

  def show
  end

  def following
    @title = "Following"
    @following = @user.following
  end

  def followers
    @title = "Followers"
    @followers = @user.followers
  end

  private
  def set_user
    @user = User.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dummy_helper.rb
module DummyHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/images/_form.html.haml
= form_for @image, :html => { multipart: true, :class => "form-horizontal image" } do |f|
  - if @image.errors.any?
    #error_expl.panel.panel-danger
      .panel-heading
        %h3.panel-title
          = pluralize(@image.errors.count, "error")
          prohibited this image from being saved:
      .panel-body
        %ul
          - @image.errors.full_messages.each do |msg|
            %li= msg
  .control-group
    = f.label :name, :class => 'control-label'
    .controls
      = f.text_field :name, :class => 'form-control'
  .control-group
    = f.label :picture, :class => 'control-label'
    .controls
      = f.file_field :picture, accept: 'image/jpeg,image/gif,image/png'
  = f.submit nil, :class => 'btn btn-primary'
  = link_to t('.cancel', :default => t("helpers.links.cancel")), images_path, :class => 'btn btn-default'

app/views/images/_image.html.haml
.col-md-3.mb-4
  .card.border-dark.ml-1.mr-1{:style => "width: 18rem;"}
    .card-body{:id => "#{dom_id image}"}
      = image_tag image.picture.url, size: "250x250"
      %p
        %strong Name:
        = link_to image.name, image
      %p
        %strong User:
        - if image.user.name?
          = image.user.name
        - else
          = image.user.email

app/views/images/edit.html.haml
%h1 Editing image
= render "form", image: @image
%br/
%div
  = link_to "Show this image", @image
  |
  \#{link_to "Back to images", images_path}

app/views/images/index.html.haml
.mb-4
  %h1 Images
  #images.card-group
    - @images.each do |image|
      = render image
  = link_to "New image", new_image_path

app/views/images/new.html.haml
%h1 New image
= render "form", image: @image
%br/
%div
  = link_to "Back to images", images_path

app/views/images/show.html.haml
= render @image
%div
  = link_to "Edit this image", edit_image_path(@image)
  |
  \#{link_to "Back to images", images_path}
  
  \#{button_to "Destroy this image", @image, method: :delete}

app/views/layouts/_navigation.html.haml
.container-fluid
  %nav.navbar.navbar-expand-lg.bg-light
    .container.d-flex.flex-row
      %a.navbar-brand{:href => "/"}
        %h3 Photo App
      - if user_signed_in?
        .container.d-flex.flex-row.justify-content-between.align-items-center
          .d-flex.justify-content-between.w-100
            .d-flex.align-items-center.justify-content-center
              = link_to "Images", images_path, class: "nav-link ps-2 pe-2"
              = link_to "Users", users_path, class: "nav-link ps-2 pe-2"
              = link_to "Followings", following_user_path(current_user), class: "nav-link ps-2 pe-2"
              = link_to "Followers", followers_user_path(current_user),  class: "nav-link ps-2 pe-2"
            .d-flex.justify-content-between.align-items-center
              = button_to "Logout", destroy_user_session_path, method: :delete, class: "btn btn-danger ps-2"
      - else
        .container.d-flex.flex-row.justify-content-between.align-items-center
          .d-flex.justify-content-between
          .d-flex.justify-content-between.align-items-center
            = button_to "Login", new_user_session_path, class: "btn btn-primary ps-2"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title PhotoApp
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = stylesheet_link_tag "https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css", media: "all", "data-turbo-track": "reload"
    = javascript_include_tag "https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js", "data-turbo-track": "reload", defer: true
    = javascript_include_tag "https://js.stripe.com/v3/"
    = javascript_importmap_tags
  %body
    = render "layouts/navigation"
    .container
      %p.notice{:style => "color: green"}= notice
      %p.alert{:style => "color: red"}= alert
      = yield

app/views/users/followers.html.haml
%h1= @title
%div
  %table.table.table-striped
    %thead
      %tr
        %th Name
        %th Email
    %tbody#followersTable
      - @followers.each do |fallower|
        %tr
          %td= fallower.name
          %td= fallower.email

app/views/users/following.html.haml
%h1= @title
%div
  %table.table.table-striped
    %thead
      %tr
        %th Name
        %th Email
    %tbody#followingTable
      - @following.each do |fallowing|
        %tr
          %td= fallowing.name
          %td= fallowing.email

app/views/users/index.html.haml
%h1 Users
%div
  %table.table.table-striped
    %thead
      %tr
        %th Name
        %th Last Name
        %th Profile
        %th Actions
    %tbody#usersTable
      - @users.each do |user|
        %tr
          %td= user.name
          %td= user.lastname
          %td= link_to "Show Profile", user_path(user), class: "btn btn-secondary"
          %td
            - if  current_user.following?(user)
              = button_to "Remove Friends List", follow_path(user), method: :delete, class: "btn btn-danger"
            - else
              = button_to "Follow this user", follows_path(followed_id: user.id), method: :post, class: "btn btn-primary"

app/views/users/show.html.haml
%h1= @user.full_name
%p
  Email: #{@user.email}

app/views/welcome/index.html.haml
- if current_user
  %h3
    Welcome: #{current_user.email}
- else
  .jumbotron
    %h2 Welcome to the Photo Management App!
    %p.lead
      You'll love managing your Photos with our application. Sign up!
  .row
    .plans.clearfix
      .col-lg-3.col-lg-offset-3.plan
        %h2 Premium Plan
        .price.pull-right
          Price: $10
        .features
          %ul
            %li Unlimited Image Uploads
            %li Responsive design
            %li Access anywhere
        %p
          = link_to 'Sign Up', new_user_registration_path, class: 'btn btn-primary sign-up'
      .col-lg-3.plan
        %h2 Amaze Plan
        .price.pull-right
          Price: $20
        .features
          %ul
            %li Unlimited Image Uploads
            %li Responsive design
            %li Access anywhere
            %li.extra Unlimited projects
        %p
          = link_to 'Sign Up', new_user_registration_path, class: 'btn btn-primary sign-up'